version: "2"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
     - "80:3000"
    links:
     - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
#  rabbitmq:
#    container_name: rabbitmq
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"